### ISSUE TITLE
Code for SHVN dataset?

### ISSUE THREAD

**Issue by deep0learning** [cedrickchee/capsule-net-pytorch#5]
Could you please provide the code for SHVN datasets?

**Comment by cedrickchee** [comment]
Hi. To be clear, my goal of open sourcing the code is to provide a better PyTorch implementation of Capsule Network *strictly* based on the paper. The paper used MNIST for the dataset. If you read the README, I do have plan to implement the paper for other dataset but this won't be soon. One of the reason why we open source our project is to get help from the community. We can only do so much in the limited time. I hope you understand my intention.

I recommend you implement the SVHN dataset yourself if you can't wait. I am happy to accept this a PR. Thank you for the great interest.

**Comment by cedrickchee** [comment]
FYI, I have modified the code to works with CIFAR10. I am closing this issue as I have not receive a response from you for almost a month now. Feel free to re-open the issue if you want to further discuss this.
