### ISSUE TITLE
Issue of squash dimension

### ISSUE THREAD

**Issue by caolusg** [cedrickchee/capsule-net-pytorch#6]
Is the squash operation applied on dimension 8 or 1152?

`return utils.squash(unit, dim=2) # dim 2 is the third dim (1152D array) in our tensor`

It seems like the squash is applied on `dim=2`, namely 1152D array but I have seen other implementation doing this on the 8D vector dimension namely `dim=1`. Is this correct?

**Comment by cedrickchee** [comment]
Hi. FYI, I am a little busy these days. I will try my best to check this and get back to you soon. If any one else here can assist me, that will be better.

I hope you don't mind my unintentional late response.

**Comment by cedrickchee** [comment]
I have checked and debugged this and found no issue. This is correct. So, closing the issue now.

**Comment by caolusg** [comment]
I agree with you, since the squash is make sure the vector length less than 1. Here the vector is 8D vector. The squash should be applied on each dim of this 8D vector.

**Comment by caolusg** [comment]
@udion I agree with you, since the squash is make sure the vector length less than 1. Here the vector is 8D vector. The squash should be applied on each dim of this 8D vector.

**Comment by udion** [comment]
The funny thing is, it works anyway. Even if I change the dim=2 to dim=1 the network is able to learn anyway. So I am wondering how @cedrickchee even checked it. Please do share, I am a newbie would like to learn the method.
